name: CI

on:
    pull_request:
    push:
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - uses: voidzero-dev/setup-vp@v1.21.1
              with:
                  node-version-file: '.node-version'
                  cache: true
            - run: vp run -r build
            - run: vp check
            - run: vp test --reporter verbose
    publish:
        if: github.ref == 'refs/heads/main'
        needs: ci
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v7
              with:
                  fetch-depth: 0
            - uses: voidzero-dev/setup-vp@v1.21.1
              with:
                  node-version-file: '.node-version'
                  cache: true
            - run: vp run -r build
            - run: vp exec noeldemartin-publish-modified-packages
